absloss_factor: 0.1
absloss_start_step: 5000
adam_beta1: 0.9
adam_beta2: 0.999
adam_eps: 1.0e-08
add_neck: true
antialias_test: 1
antialias_train: 1
augment_border_prob: 0
backbone: efficientnetv2-l
backbone_link_dim: 512
backbone_linking_layer: true
backbone_lr_factor: 0.15
backbone_warmup_steps: 2000
background_aug_prob: 0.7
base_learning_rate: 0.0002121
batch_renorm: true
batch_size: 32
batch_size_2d: 32
batch_size_densepose: 20
batch_size_parametric: 64
batch_size_test: 150
beta_nll: 1
border_value: 0
box_size_m: 2.2
centered_stride: true
charb_eps: 0
checkpoint_dir: .//experiments/.//experiments/default_logdir
checkpoint_period: 2000
clip_grad_norm_histsize: 100
clip_grad_norm_median_factor: null
clip_grad_norm_quantile: 0.75
color_aug: true
comment: null
completed_steps: null
config_file: null
constrain_kernel_norm: 20
constraint_rate: 1
cosine_cooldown: false
custom: ''
data_format: NHWC
dataset2d: mpii
dataset3d: h36m
dataset3d_kp: null
dataset_dense: null
decay_field: false
depth: 8
depth_on_2d_heatmap: true
dtype: bfloat16
dual_finetune_lr: false
dynamic_loss_scale: false
ema_momentum: 1
export_file: null
field_hidden_layers: 1
field_hidden_size: 384
field_lr_factor: 1
field_posenc_dim: 1024
field_type: gps
file: null
finetune_gps: true
finetune_in_inference_mode: 0
fitter_smpl_config:
  J_regressor_post_lbs:
  - 24
  - 1024
  J_shapedirs:
  - 24
  - 3
  - 10
  J_template:
  - 24
  - 3
  kid_J_shapedir:
  - 24
  - 3
  kid_shapedir:
  - 1024
  - 3
  kintree_parents:
  - 4294967295
  - 0
  - 0
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 9
  - 9
  - 12
  - 13
  - 14
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  kintree_parents_tensor:
  - 24
  num_betas: 10
  num_joints: 24
  num_vertices: 1024
  posedirs:
  - 1024
  - 3
  - 207
  shapedirs:
  - 1024
  - 3
  - 10
  v_template:
  - 1024
  - 3
  weights:
  - 1024
  - 24
fitter_smplx_config:
  J_regressor_post_lbs:
  - 55
  - 1024
  J_shapedirs:
  - 55
  - 3
  - 10
  J_template:
  - 55
  - 3
  kid_J_shapedir:
  - 55
  - 3
  kid_shapedir:
  - 1024
  - 3
  kintree_parents:
  - 4294967295
  - 0
  - 0
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 9
  - 9
  - 12
  - 13
  - 14
  - 16
  - 17
  - 18
  - 19
  - 15
  - 15
  - 15
  - 20
  - 25
  - 26
  - 20
  - 28
  - 29
  - 20
  - 31
  - 32
  - 20
  - 34
  - 35
  - 20
  - 37
  - 38
  - 21
  - 40
  - 41
  - 21
  - 43
  - 44
  - 21
  - 46
  - 47
  - 21
  - 49
  - 50
  - 21
  - 52
  - 53
  kintree_parents_tensor:
  - 55
  num_betas: 10
  num_joints: 55
  num_vertices: 1024
  posedirs:
  - 1024
  - 3
  - 486
  shapedirs:
  - 1024
  - 3
  - 10
  v_template:
  - 1024
  - 3
  weights:
  - 1024
  - 55
fix_uncert_factor: false
force_grad_accum: false
frozen_backbone_steps: 3000
full_rot_aug_prob: 0.1
fullpersp_l2_regul: 0.0001
geom_aug: true
ghost_bn: ''
gps_eps: 1.0e-06
gps_maxi: null
gps_mini: null
gps_norm_mode: dynamic
grad_accum_steps: 1
group_norm: false
hflip_aug: true
image_barecat_path: null
image_interpolation_test: linear
image_interpolation_train: linear
init_lbo: true
init_path: null
input_model_path: null
jpeg_aug_prob: 0.25
lbo_concat_coord: false
lbo_eigval_regul: 0.0001
lbo_zero_first: false
load_backbone_from: null
load_path: null
logdir: .//experiments/default_logdir
loglevel: info
lora_rank: 0
loss_factor_2d: 0.1
loss_factor_dense: 0.05
loss_factor_kp: 0.75
loss_factor_param: 1.0
loss_scale: 128
lr_cooldown_fraction: 0.08
lr_warmup_steps: 1000
mean_relative: true
mix_3d_inside_fov: 0.5
multi_gpu: false
nll_loss: true
norm_loss_factor: 0.0
norm_loss_ramp_steps: 4000
norm_loss_start_step: 1000
num_internal_points: 384
num_points: 1024
num_surface_points: 640
occlude_aug_prob: 0.5
occlude_aug_prob_2d: 0.7
occlude_aug_scale: 1
optimizer: adamw
output_model_path: null
pad_white_pixels: false
partial_visibility_prob: 0.15
patch_embed_lr_factor: 0.2
pred_path: .//experiments/.//experiments/default_logdir/predictions_h36m.npz
predict: false
proc_side: 384
render: false
render_callback_period: 100
renorm_limit_scale: 1
rewarm_start_step: null
rot_aug: 20
scale_aug_down: 25
scale_aug_up: 25
seed: 1
shift_aug: 10
sigma_reparam: false
smpl_config:
  J_regressor_post_lbs:
  - 24
  - 6890
  J_shapedirs:
  - 24
  - 3
  - 10
  J_template:
  - 24
  - 3
  cano_all:
  - 1048
  - 3
  kid_J_shapedir:
  - 24
  - 3
  kid_shapedir:
  - 6890
  - 3
  kintree_parents:
  - 4294967295
  - 0
  - 0
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 9
  - 9
  - 12
  - 13
  - 14
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  kintree_parents_tensor:
  - 24
  num_betas: 10
  num_joints: 24
  num_vertices: 6890
  posedirs:
  - 6890
  - 3
  - 207
  shapedirs:
  - 6890
  - 3
  - 10
  v_template:
  - 6890
  - 3
  weights:
  - 6890
  - 24
smplx_config:
  J_regressor_post_lbs:
  - 55
  - 10475
  J_shapedirs:
  - 55
  - 3
  - 10
  J_template:
  - 55
  - 3
  cano_all:
  - 1079
  - 3
  kid_J_shapedir:
  - 55
  - 3
  kid_shapedir:
  - 10475
  - 3
  kintree_parents:
  - 4294967295
  - 0
  - 0
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 9
  - 9
  - 12
  - 13
  - 14
  - 16
  - 17
  - 18
  - 19
  - 15
  - 15
  - 15
  - 20
  - 25
  - 26
  - 20
  - 28
  - 29
  - 20
  - 31
  - 32
  - 20
  - 34
  - 35
  - 20
  - 37
  - 38
  - 21
  - 40
  - 41
  - 21
  - 43
  - 44
  - 21
  - 46
  - 47
  - 21
  - 49
  - 50
  - 21
  - 52
  - 53
  kintree_parents_tensor:
  - 55
  num_betas: 10
  num_joints: 55
  num_vertices: 10475
  posedirs:
  - 10475
  - 3
  - 486
  shapedirs:
  - 10475
  - 3
  - 10
  v_template:
  - 10475
  - 3
  weights:
  - 10475
  - 55
stop_step: null
stride_test: 32
stride_train: 32
test_aug: false
test_on: test
test_subjects: null
test_time_mirror_aug: false
train: false
train_on: train
train_subjects: null
trainable_canonical_joints: true
training_steps: null
transition_bn: false
uncert_bias: 0.0
uncert_bias2: 0.001
unfreeze_parts_step: 0
valid_subjects: null
validate_on: valid
validate_period: null
viz: false
wandb_project: localizerfield
weak_perspective: false
weight_decay: 0.003
workers: null
